#!/bin/bash
start=$SECONDS
while true
do
    cd /home/nero/ptx
    echo "Starting Service"        
    ./busNear.py $1
    echo "____________________________"

    if [ ! -f ./stop ]; then
        echo "Service out.."
        echo "Timer:" + $((SECONDS - start))
    else
        echo "Stop file effected !"
        break
    fi
done
